
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package shmodmaker;

import java.io.BufferedReader;
import java.io.File;
import java.io.FileReader;
import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Paths;
/**
 *
 * @author David
 */
public class MainWindow extends javax.swing.JFrame {

    /**
     * Creates new form MainWindow
     */
    public MainWindow() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tabbed_pane = new javax.swing.JTabbedPane();
        tab_armor = new javax.swing.JPanel();
        lbl_armor = new javax.swing.JLabel();
        tab_bush = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        tab_crop = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        tab_enemy = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        tab_faction = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        tab_farmAnimal = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        tab_flower = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        tab_job = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        tab_tree = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        tab_weapon = new javax.swing.JPanel();
        lbl_weapon = new javax.swing.JLabel();
        btn_weapon = new javax.swing.JButton();
        tab_wildAnimal = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        tabbed_pane.setTabPlacement(javax.swing.JTabbedPane.LEFT);
        tabbed_pane.setMinimumSize(new java.awt.Dimension(0, 0));

        lbl_armor.setText("N/A");

        javax.swing.GroupLayout tab_armorLayout = new javax.swing.GroupLayout(tab_armor);
        tab_armor.setLayout(tab_armorLayout);
        tab_armorLayout.setHorizontalGroup(
            tab_armorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tab_armorLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbl_armor)
                .addContainerGap(464, Short.MAX_VALUE))
        );
        tab_armorLayout.setVerticalGroup(
            tab_armorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tab_armorLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbl_armor)
                .addContainerGap(291, Short.MAX_VALUE))
        );

        tabbed_pane.addTab("Armor", tab_armor);

        jLabel7.setText("N/A");

        javax.swing.GroupLayout tab_bushLayout = new javax.swing.GroupLayout(tab_bush);
        tab_bush.setLayout(tab_bushLayout);
        tab_bushLayout.setHorizontalGroup(
            tab_bushLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tab_bushLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7)
                .addContainerGap(464, Short.MAX_VALUE))
        );
        tab_bushLayout.setVerticalGroup(
            tab_bushLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tab_bushLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7)
                .addContainerGap(291, Short.MAX_VALUE))
        );

        tabbed_pane.addTab("Bush", tab_bush);

        jLabel6.setText("N/A");

        javax.swing.GroupLayout tab_cropLayout = new javax.swing.GroupLayout(tab_crop);
        tab_crop.setLayout(tab_cropLayout);
        tab_cropLayout.setHorizontalGroup(
            tab_cropLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tab_cropLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6)
                .addContainerGap(464, Short.MAX_VALUE))
        );
        tab_cropLayout.setVerticalGroup(
            tab_cropLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tab_cropLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6)
                .addContainerGap(291, Short.MAX_VALUE))
        );

        tabbed_pane.addTab("Crop", tab_crop);

        jLabel11.setText("N/A");

        javax.swing.GroupLayout tab_enemyLayout = new javax.swing.GroupLayout(tab_enemy);
        tab_enemy.setLayout(tab_enemyLayout);
        tab_enemyLayout.setHorizontalGroup(
            tab_enemyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tab_enemyLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel11)
                .addContainerGap(464, Short.MAX_VALUE))
        );
        tab_enemyLayout.setVerticalGroup(
            tab_enemyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tab_enemyLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel11)
                .addContainerGap(291, Short.MAX_VALUE))
        );

        tabbed_pane.addTab("Enemy", tab_enemy);

        jLabel5.setText("N/A");

        javax.swing.GroupLayout tab_factionLayout = new javax.swing.GroupLayout(tab_faction);
        tab_faction.setLayout(tab_factionLayout);
        tab_factionLayout.setHorizontalGroup(
            tab_factionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tab_factionLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addContainerGap(464, Short.MAX_VALUE))
        );
        tab_factionLayout.setVerticalGroup(
            tab_factionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tab_factionLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addContainerGap(291, Short.MAX_VALUE))
        );

        tabbed_pane.addTab("Faction", tab_faction);

        jLabel10.setText("N/A");

        javax.swing.GroupLayout tab_farmAnimalLayout = new javax.swing.GroupLayout(tab_farmAnimal);
        tab_farmAnimal.setLayout(tab_farmAnimalLayout);
        tab_farmAnimalLayout.setHorizontalGroup(
            tab_farmAnimalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tab_farmAnimalLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel10)
                .addContainerGap(464, Short.MAX_VALUE))
        );
        tab_farmAnimalLayout.setVerticalGroup(
            tab_farmAnimalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tab_farmAnimalLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel10)
                .addContainerGap(291, Short.MAX_VALUE))
        );

        tabbed_pane.addTab("Farm Animal", tab_farmAnimal);

        jLabel4.setText("N/A");

        javax.swing.GroupLayout tab_flowerLayout = new javax.swing.GroupLayout(tab_flower);
        tab_flower.setLayout(tab_flowerLayout);
        tab_flowerLayout.setHorizontalGroup(
            tab_flowerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tab_flowerLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addContainerGap(464, Short.MAX_VALUE))
        );
        tab_flowerLayout.setVerticalGroup(
            tab_flowerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tab_flowerLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addContainerGap(291, Short.MAX_VALUE))
        );

        tabbed_pane.addTab("Flower", tab_flower);

        jLabel3.setText("N/A");

        javax.swing.GroupLayout tab_jobLayout = new javax.swing.GroupLayout(tab_job);
        tab_job.setLayout(tab_jobLayout);
        tab_jobLayout.setHorizontalGroup(
            tab_jobLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tab_jobLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addContainerGap(464, Short.MAX_VALUE))
        );
        tab_jobLayout.setVerticalGroup(
            tab_jobLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tab_jobLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addContainerGap(291, Short.MAX_VALUE))
        );

        tabbed_pane.addTab("Job", tab_job);

        jLabel2.setText("N/A");

        javax.swing.GroupLayout tab_treeLayout = new javax.swing.GroupLayout(tab_tree);
        tab_tree.setLayout(tab_treeLayout);
        tab_treeLayout.setHorizontalGroup(
            tab_treeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tab_treeLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addContainerGap(464, Short.MAX_VALUE))
        );
        tab_treeLayout.setVerticalGroup(
            tab_treeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tab_treeLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addContainerGap(291, Short.MAX_VALUE))
        );

        tabbed_pane.addTab("Tree", tab_tree);

        lbl_weapon.setText("N/A");

        btn_weapon.setText("Add Weapon");
        btn_weapon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_weaponActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout tab_weaponLayout = new javax.swing.GroupLayout(tab_weapon);
        tab_weapon.setLayout(tab_weaponLayout);
        tab_weaponLayout.setHorizontalGroup(
            tab_weaponLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tab_weaponLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(tab_weaponLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(tab_weaponLayout.createSequentialGroup()
                        .addComponent(lbl_weapon)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(btn_weapon, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 472, Short.MAX_VALUE))
                .addContainerGap())
        );
        tab_weaponLayout.setVerticalGroup(
            tab_weaponLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tab_weaponLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbl_weapon)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 257, Short.MAX_VALUE)
                .addComponent(btn_weapon)
                .addContainerGap())
        );

        tabbed_pane.addTab("Weapon", tab_weapon);

        jLabel9.setText("N/A");

        javax.swing.GroupLayout tab_wildAnimalLayout = new javax.swing.GroupLayout(tab_wildAnimal);
        tab_wildAnimal.setLayout(tab_wildAnimalLayout);
        tab_wildAnimalLayout.setHorizontalGroup(
            tab_wildAnimalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tab_wildAnimalLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel9)
                .addContainerGap(464, Short.MAX_VALUE))
        );
        tab_wildAnimalLayout.setVerticalGroup(
            tab_wildAnimalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tab_wildAnimalLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel9)
                .addContainerGap(291, Short.MAX_VALUE))
        );

        tabbed_pane.addTab("Wild Animal", tab_wildAnimal);

        jMenu1.setText("File");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tabbed_pane, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(35, Short.MAX_VALUE)
                .addComponent(tabbed_pane, javax.swing.GroupLayout.PREFERRED_SIZE, 321, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        tabbed_pane.getAccessibleContext().setAccessibleName("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
    }//GEN-LAST:event_formWindowOpened

    private void btn_weaponActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_weaponActionPerformed
        // TODO add your handling code here:
        
        //build parser ref
        
        //get JSON files
        
        //parse files
        
        //save files
            //check that mod folder exsists
        
        //edit manifest.json for mod
        
        String string = "";
        File myFile = new File("");
        System.out.println(myFile.getAbsolutePath()+"\\JSONs\\Armor\\Armor.json");
        
        try
        {
            string = new String(Files.readAllBytes(Paths.get(".\\JSONS\\Armor\\Armor.json")));
        } catch (IOException e )
        {
            System.err.println("Caught IOException: " + e.getMessage());
        }
        
        lbl_weapon.setText(string);
        System.out.println(string);
        
        String[] lines = string.split(System.getProperty("line.separator"));
        for(int i = 0; i < lines.length; i++)
        {
            System.out.println(lines[i]);
            
        }
    }//GEN-LAST:event_btn_weaponActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainWindow().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_weapon;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JLabel lbl_armor;
    private javax.swing.JLabel lbl_weapon;
    private javax.swing.JPanel tab_armor;
    private javax.swing.JPanel tab_bush;
    private javax.swing.JPanel tab_crop;
    private javax.swing.JPanel tab_enemy;
    private javax.swing.JPanel tab_faction;
    private javax.swing.JPanel tab_farmAnimal;
    private javax.swing.JPanel tab_flower;
    private javax.swing.JPanel tab_job;
    private javax.swing.JPanel tab_tree;
    private javax.swing.JPanel tab_weapon;
    private javax.swing.JPanel tab_wildAnimal;
    private javax.swing.JTabbedPane tabbed_pane;
    // End of variables declaration//GEN-END:variables

    public String parse(String str, String[] ref)
    {
        
        return str;
    }
}
